### ISSUE TITLE
error in the example ? 

### ISSUE THREAD

**Issue by alexlib** [ronshnapp/MyPTV#6]
@ronshnapp 

`(myptv) PS C:\Users\alex\repos\MyPTV\example> python workflow.py params_file.yml calibration

 given inputs -
params file name: params_file.yml
action: calibration

camera files not detected in the working directory.
Generating a new empty file and leaving calib. sequence.
To continue calibration, fill in an initial guess in the
empty file, and then run again the calibration sequence.
Traceback (most recent call last):
  File "C:\Users\alex\repos\MyPTV\example\workflow.py", line 575, in <module>
    wf = workflow(fname, action)
  File "C:\Users\alex\repos\MyPTV\example\workflow.py", line 63, in __init__
    self.calibration_sequence()
  File "C:\Users\alex\repos\MyPTV\example\workflow.py", line 261, in calibration_sequence
    cam.save('.')
UnboundLocalError: local variable 'cam' referenced before assignment`

**Comment by ronshnapp** [comment]
Sorry, my bug, this should now be fixed.

**Comment by alexlib** [comment]
I do not see the initial guess files, maybe that's what is missing? The error message changed, but the bug is still there. I couldn't follow the manual 

`(myptv) PS C:\Users\alex\repos\MyPTV\example> python workflow.py .\params_file.yml calibration

 given inputs -
params file name: .\params_file.yml
action: calibration


camera files not detected in the working directory.
Generating a new empty file and leaving calib. sequence.
To continue calibration, fill in an initial guess in the
empty file, and then run again the calibration sequence.
Traceback (most recent call last):
  File "C:\Users\alex\repos\MyPTV\example\workflow.py", line 576, in <module>
    wf = workflow(fname, action)
  File "C:\Users\alex\repos\MyPTV\example\workflow.py", line 63, in __init__
    self.calibration_sequence()
  File "C:\Users\alex\repos\MyPTV\example\workflow.py", line 262, in calibration_sequence
    cam.save('.')
  File "c:\users\alex\repos\myptv\myptv\imaging_mod.py", line 291, in save
    f = open(full_path, 'w')
PermissionError: [Errno 13] Permission denied: '.\\cam1'
